Increment1 2 3
Jay-T/go-devops pull request #1
Opened 2021-11-21 14:48 UTC by Jay-T

Sprint 1

2021-11-22 15:29 UTC, Barugoo commented on cmd/agent/main.go
> +	url := fmt.Sprintf("http://127.0.0.1:8080/update/%s/%s/%f", g.typename, g.name, g.value)
Давай вынесем вот эту часть урла -> `http://127.0.0.1:8080` отдельно в константу, чтобы можно было легко поменять хост сервера в одном месте, без необходимости искать все вхождения этой строки в коде проекта.

2021-11-22 15:32 UTC, Barugoo commented on cmd/agent/main.go
> +		fmt.Println(err)
Для логгирования лучше использовать пакет `log`
Причины две:
1. `log` добавляет к каждому сообщению временную метку
2. `log`, в отличии от библиотеки `fmt`, позволяет перенаправить печать сообщений в произвольный интерфейс `io.Writer` (это может быть как открытый файл, так и tcp подключение). В `fmt` сообщения печатаются только `stdout`

2021-11-22 15:36 UTC, Barugoo commented on cmd/agent/main.go
> +	resp.Body.Close()
А если у нас на 31 строке произошла ошибка и функция завершилась не дойдя до сюда? 
В этом случае тело запроса останется открытым => пакет `net/http` не даст переиспользовать подключение. 

Проблема в том, что процессу доступно ограниченное количество подключений, и если их не переиспользовать, то они могут закончится. Это иногда называют "утечкой подключений"

Чтобы этого избежать, обычно вызывают метод `Close` вместе с `defer`: 
```go
resp, err := client.Post(url, "text/plain", nil)
if err != nil {
        fmt.Println(err)
        return false, err
}
defer resp.Body.Close()
```

2021-11-22 15:53 UTC, Barugoo commented on cmd/agent/main.go
> +			{name: "Alloc", typename: "gauge", value: float64(rtm.Alloc)},
Вкусовщина, но я бы завернул инициализацию объектов `gauge` или `counter` в функции, для лучшей читаемости:
```go

const (
        metricTypeGauge = "gauge"
        metricTypeCounter = "counter"
)

func newGauge(name string, value float64) gauge {
        return gauge{name:name, typename: metricTypeGauge, value: value}
}
//...
metrics := []gauge{
	newGauge("Frees", float64(rtm.Frees)),
 	newGauge("GCCPUFraction", float64(rtm.GCCPUFraction)),
//...

2021-11-22 15:55 UTC, Barugoo commented on cmd/agent/main.go
> +type counter struct {
У этих структур совпадают все поля, кроме типа `value`
Может быть мы можем как-то объединить эти структуры в одну, чтобы не поддерживать две?

2021-11-22 15:55 UTC, Barugoo commented on cmd/agent/main.go
> +		if PollCount%5 == 0 {
Что за магическая цифра "5"?=)
Давай вынесем в именованную константу

2021-11-22 15:56 UTC, Barugoo commented on cmd/agent/main.go
> +}
Ты сделал graceful shutdown, круто! Но давай пойдем дальше и попробуем как-то подружить эту логику с отменой контекста?

2021-11-22 15:58 UTC, Barugoo commented on cmd/agent/main_test.go
> +				log.Fatal(err)
Давай обработаем эту ошибку с помощью методов testing.T?

2021-11-22 15:58 UTC, Barugoo commented on cmd/agent/main_test.go
> +				log.Fatal(err)
Ну и кстати я бы поосветовал все же переделать тесты c использованием либы `testify` - она удобная!

2021-11-22 16:03 UTC, Barugoo commented on cmd/agent/main_test.go
> +			if (err != nil) != tt.wantErr {
Лучше чтобы лучше читалось разобьем проверку ошибки:
 `if err != nil && !tt.WantErr {...}`  - если не ждем ошибку
 `if err == nil && tt.WantErr {...}`  - если ждем ошибку

2021-11-22 16:04 UTC, Barugoo commented on cmd/server/main.go
> +const HTMLPage = `
Лучше вынести из main.go в отдельный go-файл 
А лучше в .html файл и подсасывать его в память при старте сервера

2021-11-22 16:04 UTC, Barugoo commented on cmd/server/main.go
> +const HTMLPage = `
Круто что ты заморочился с веб-мордой, кстати!

2021-11-22 16:10 UTC, Barugoo commented on cmd/server/main.go
> +	}
`else` здесь не нужен)

```go
if err != nil {
    http.Error(w, "parsing error. Bad request", http.StatusBadRequest)
    return
}
gmetrics[mName] = gauge{v: value}
w.Header().Add("Content-Type", "application/json")
w.WriteHeader(http.StatusOK)
```

2021-11-22 16:10 UTC, Barugoo commented on cmd/server/main.go
> +		w.Header().Add("Content-Type", "application/json")
Мне кажется здесь это лишнее)

2021-11-22 16:17 UTC, Barugoo commented on cmd/server/main.go
> +	http.Error(w, "Uknown type", http.StatusNotImplemented)
Аккуратнее со статусами! У них у всех есть четкие границы использования и кейсы в которых клиент ожидает получить те или иные статусы.
`http.StatusNotImplemented` относится к 5хх классу статус-кодов, то есть он сигнализирует об ошибках на сервере, связанных с тем, что клиент пытается вызвать неподдерживаемую логику, которая  **_должна быть_** поддерживаемой сервером. В данном случае, интерфейс твоего сервера предписывает, что эндпоинта /update/* на севере нет и клиент его ожидать не должен.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501

tl;dr используй `StatusBadRequest`

2021-11-22 16:20 UTC, Barugoo commented on cmd/server/main.go
> +	r.Post("/update/*", NotImplemented)
А если у тебя станет в 10 раз больше эндпоинтов и их сочетаний? И почему ты делаешь fallback-ручки только для метода POST? А как же GET, PUT, UPDATE, HEAD и так далее?  
Если серьезно - не нужно прописывать fallback-сценарии для всех возможных вариаций эндпоинтов: роутер сам хэндлит несуществующие пути в твоем сервере

Но круто, что ты задумался об этом!

2021-11-22 16:20 UTC, Barugoo commented on cmd/server/main.go
> +		Addr:    ":8080",
Давай вынесем в константу

2021-11-22 16:20 UTC, Barugoo commented on cmd/server/main.go
> +	log.Printf("Listening on port 8080")
И будем сюда подставлять эту константу вместо 8080

2021-11-22 16:21 UTC, Barugoo requested changes
Круто! Но я бы хотел чтобы ты слегка отполировал код) Жду доработок!

2021-11-22 19:33 UTC, Jay-T commented on cmd/server/main.go
> +	http.Error(w, "Uknown type", http.StatusNotImplemented)
Я бы да, но тест явно ожидает 501 в одном из тесткейсов.

2021-11-22 19:34 UTC, Jay-T commented on cmd/server/main.go
> +	r.Post("/update/*", NotImplemented)
Это опять идет из тесткейсов. Просто так сверх задания я бы это описывать не стал и оставил дефолтный 404 :)

2021-11-27 10:35 UTC, Jay-T commented on cmd/agent/main.go
> +	url := fmt.Sprintf("http://127.0.0.1:8080/update/%s/%s/%f", g.typename, g.name, g.value)
fixed

2021-11-27 10:35 UTC, Jay-T commented on cmd/agent/main.go
> +		fmt.Println(err)
fixed

2021-11-27 10:35 UTC, Jay-T commented on cmd/agent/main.go
> +	resp.Body.Close()
fixed

2021-11-27 10:35 UTC, Jay-T commented on cmd/agent/main.go
> +			{name: "Alloc", typename: "gauge", value: float64(rtm.Alloc)},
fixed

2021-11-27 10:35 UTC, Jay-T commented on cmd/agent/main.go
> +type counter struct {
fixed

2021-11-27 10:36 UTC, Jay-T commented on cmd/agent/main.go
> +		if PollCount%5 == 0 {
Это чтоб 10 секунд отсчитать. :) 
Вынес в константу. fixed

2021-11-27 10:39 UTC, Jay-T commented on cmd/agent/main.go
> +}
Прокинул контекст в getData. Там только нюанс в том, что логгер не пишет сообщение в stdout оттуда при завершении контекста, а fmt пишет. Понимаю, что логгер будет писать в файл в итоге, но решил пока оставить так.

В серверной части контекст не делал. Там, думаю, его уместно передавать в хендлеры, которые потенциально могут выполнять запросы в базы или делать какие-либо долгие расчеты. Пока там нигде не добавлял контекст - посмотрю, какие задания будут дальше и решу, где добавить, если вы не против.

would say fixed

2021-11-27 10:39 UTC, Jay-T commented on cmd/agent/main_test.go
> +				log.Fatal(err)
fixed

2021-11-27 10:40 UTC, Jay-T commented on cmd/agent/main_test.go
> +			if (err != nil) != tt.wantErr {
убрал это при переделке на assert/require

2021-11-27 10:40 UTC, Jay-T commented on cmd/agent/main_test.go
> +			if (err != nil) != tt.wantErr {
fixed

2021-11-27 10:40 UTC, Jay-T commented on cmd/server/main.go
> +const HTMLPage = `
fixed

2021-11-27 10:40 UTC, Jay-T commented on cmd/server/main.go
> +	}
fixed

2021-11-27 10:40 UTC, Jay-T commented on cmd/server/main.go
> +		w.Header().Add("Content-Type", "application/json")
fixed

2021-11-27 10:41 UTC, Jay-T commented on cmd/server/main.go
> +	http.Error(w, "Uknown type", http.StatusNotImplemented)
тут ничего не делал, т.к., еще раз повторюсь, автотесты требуют 501 ошибку кое-где.

2021-11-27 10:41 UTC, Jay-T commented on cmd/server/main.go
> +	r.Post("/update/*", NotImplemented)
same as previous

2021-11-27 10:41 UTC, Jay-T commented on cmd/server/main.go
> +		Addr:    ":8080",
fixed

2021-11-27 10:41 UTC, Jay-T commented on cmd/server/main.go
> +	log.Printf("Listening on port 8080")
fixed

2021-11-30 10:09 UTC, Barugoo commented on cmd/server/main.go
> +	http.Error(w, "Uknown type", http.StatusNotImplemented)
Спасибо, что подсветил это! Вынесу на обсуждение с авторами

2021-11-30 10:10 UTC, Barugoo commented on cmd/server/main.go
> +	r.Post("/update/*", NotImplemented)
Понял, спасибо!

2021-11-30 10:14 UTC, Barugoo approved these changes
Круто! Спасибо, что подсветил момент со статусами в автотестах, обсудим с авторами)

2021-11-30 10:33 UTC, merged